SELECT
CASE
WHEN S.Marks < 70 THEN NULL
ELSE S.Name
END AS Name_or_NULL,
CASE
WHEN S.Marks >= 90 THEN 10
ELSE LEFT(S.Marks+10, 1)
END AS Grade,
S.Marks
FROM STUDENTS S
ORDER BY CAST(Grade AS UNSIGNED) DESC, Name_or_NULL, S.Marks
