SELECT DISTINCT *
FROM FUNCTIONS F1
WHERE
(
    F1.X = F1.Y
    AND
    (SELECT COUNT(F2.X) FROM FUNCTIONS F2 WHERE F2.X = F1.X AND F2.Y = F1.Y) > 1  
) OR
(
    F1.X < F1.Y
    AND
    EXISTS(SELECT 1 FROM FUNCTIONS F2 WHERE F2.X = F1.Y AND F2.Y = F1.X)
)
ORDER BY X